# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: ssosync
version: 2

before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
      - GOAMD64=v1 # explicit default
      - GOARM64=v8.2
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "386"
    ldflags:
      - -s -w -X github.com/awslabs/ssosync/cmd.version={{.Version}} -X github.com/awslabs/ssosync/cmd.commit={{.Commit}} -X github.com/awslabs/ssosync/cmd.date={{.Date}} -X github.com/awslabs/ssosync/cmd.builtBy=goreleaser
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        formats:
          - zip

kos:
  - repositories:
      - ghcr.io/awslabs/ssosync
    tags:
      - "{{.Version}}"
      - latest
    sbom_directory: "dist/sbom"
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
docker_signs:
  - artifacts: manifests
