AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Description: |
  This CloudFormation template will deploy an instance of the SSOSync-Staging
  candidate releases (via privately shared app in the AWS Serverless Application
  Repository (SAR) within the Staging Account.
Parameters:
  AppArn:
    Description: The candidate release in the SAR
    #Default: "arn:aws:serverlessrepo:<AWS::Region>:<AccountId>:applications/<ApplicationName>"
    Type: String
  AppVersionParam:
    Description: The version of this build in SAR
    #Default: "/SSOSync/Staging/Version"
    Type: String
  GoogleServiceCredentialsSecret:
    Type: String
  SCIMEndpointUrlParam:
    Type: String
    Default: /SSOSync/aws/SCIMEndpointUrl
  SCIMAccessTokenSecret:
    Type: String
  SecretRegionParam:
    Type: String
    Default: /SSOSync/aws/Region
  IdentityStoreIdParam:
    Type: String
    Default: /SSOSync/aws/IdentityStoreId
  GroupMatch:
    Description: The search string to match Groups in Google Workspace
    Default: "name:AWS*"
    Type: String

Resources:
  SARApp:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: !Ref AppArn
        SemanticVersion: !Ref AppVersion
      Parameters:
        FunctionName: SSOSyncFunction
        GoogleCredentials: !Join
          - ""
          - - "{{resolve:secretsmanager:"
            - !Ref GoogleServiceCredentialsSecret
            - "}}"
        SCIMEndpointUrl: !Join
          - ""
          - - "{{resolve:ssm:"
            - !Ref SCIMEndpointUrlParam
            - "}}"
        SCIMEndpointAccessToken: !Join
          - ""
          - - "{{resolve:secretsmanager:"
            - !Ref SCIMAccessTokenSecret
            - "}}"
        Region: !Join
          - ""
          - - "{{resolve:ssm:"
            - !Ref SecretRegionParam
            - "}}"
        IdentityStoreID: !Join
          - ""
          - - "{{resolve:ssm:"
            - !Ref IdentityStoreIdParam
            - "}}"
        SyncMethod: groups
        GoogleGroupMatch: !Ref GroupMatch
        LogLevel: info
        LogFormat: json
