
# .github/workflows/main.yaml
name: main

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.3.1
          args: --timeout=5m
      
      - name: Run Tests
        run: go test -cover -p 1 -race -v ./...
